[package]
name = "retroveneer"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
tokio = { version = "1.42.0", features = ["full"] }
raylib = { git = "https://github.com/raylib-rs/raylib-rs", branch = "unstable", features = ["opengl_es_20"] }